baseURL = "https://jefflinse.io"
title = "Jeff Linse"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

#disqusShortname = "yourdiscussshortname"
googleAnalytics = "G-X3LFE83NPE"

[params]
    author = "Jeff Linse"
    #description = ""
    keywords = "jeff,linse,jefflinse,jlinse,software,developer,personal,box"
    info = "Full Stack Software Developer"
    avatarURL = "images/avatar.jpg"
    #gravatar = "name@example.com"
    #footerContent = "Enter a text here."

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "light"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom SCSS
    customSCSS = ["scss/overrides.scss"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/jefflinse"
#[[params.social]]
#    name = "Twitter"
#    icon = "fa fa-twitter"
#    weight = 3
#    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/jefflinse"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = false
        noClasses = true
        style = "friendly"
        tabWidth = 4

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 1
            url = "projects/"
